services:
  - type: web
    name: applet-suite-backend
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: JAVA_VERSION
        value: 21